### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sdevriese** [ubcgif/em1dfm#1]
![image](https://user-images.githubusercontent.com/13733333/41370771-5d5d9f36-6efd-11e8-9a6a-f8e1990a16ab.png)

The manual says "3D inversions of magnetic data" while this should be 1D inversions of frequency-domain EM data.

**Comment by dccowan** [comment]
Nice catch. I have made the change to "effective and efficient 1D inversions of electromagnetic data"
